apiVersion: v1
kind: Service
metadata:
  name: devops-jenkins-agent
  namespace: kubesphere-devops-system
spec:
  ports:
  - name: jnlp
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
  type: ClusterIP