apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-agent
  name: jenkins-agent
  namespace: kubesphere-devops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-agent
    spec:
      containers:
      - image: kubespheredev/devops-controller:dev-v3.2.1-rc.3-6726130
        name: controller
        args:
        - --enabled-controllers
        - all=false,jenkinsagent=true,jenkinsconfig=true
        volumeMounts:
        - mountPath: /etc/kubesphere/
          name: kubesphere-config
        resources: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: devops-config
        name: kubesphere-config