apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - podtemplates
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - devopsprojects
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelineruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
